import { wu, cd } from '../helpers.js'

// Anaerobic Capacity workouts. See src/data/workouts.js for the field reference.
export const anaerobic = [
  {
    id: 'ana-1',
    headline: '18 x 40/20 @ 150% FTP',
    title: 'Anaerobic 40/20s',
    category: 'anaerobic',
    subcategory: 'repeats',
    level: 'advanced',
    tss: 75,
    description: 'Brutal on/off efforts to build anaerobic capacity and repeatability.',
    steps: [
      '15 min warm-up',
      '3 sets of 6 x (40 s @ 150% FTP, 20 s easy), 5 min between sets',
      '8 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 6, trailingOff: true, on: { d: 40, p: 1.5 }, off: { d: 20, p: 0.5 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 6, trailingOff: true, on: { d: 40, p: 1.5 }, off: { d: 20, p: 0.5 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 6, trailingOff: true, on: { d: 40, p: 1.5 }, off: { d: 20, p: 0.5 } },
      cd(480),
    ],
  },
  {
    id: 'ana-2',
    headline: '8 x 15 s sprints',
    title: 'Sprint Repeats',
    category: 'anaerobic',
    subcategory: 'sprints',
    level: 'intermediate',
    tss: 55,
    description: 'Maximal short sprints with full recovery to develop peak power.',
    steps: [
      '15 min warm-up',
      '8 x 15 s all-out sprint, 4 min easy spin between',
      '6 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 8, on: { d: 15, p: 2.0 }, off: { d: 240, p: 0.5 } },
      cd(360),
    ],
  },
  {
    id: 'ana-3',
    headline: '6 x 1 min @ 140–160% FTP',
    title: 'Capacity 1-min Blasts',
    category: 'anaerobic',
    subcategory: 'efforts',
    level: 'advanced',
    tss: 80,
    description: 'One-minute maximal efforts that hurt — for race-winning capacity.',
    steps: [
      '18 min warm-up',
      '6 x 1 min @ 140–160% FTP all-out, 5 min easy between',
      '7 min cool-down',
    ],
    intervals: [
      wu(1080),
      { repeat: 6, on: { d: 60, p: 1.5 }, off: { d: 300, p: 0.5 } },
      cd(420),
    ],
  },
  {
    id: 'ana-4',
    headline: '6 x 10 s standing starts',
    title: 'Standing Start Power',
    category: 'anaerobic',
    subcategory: 'sprints',
    level: 'beginner',
    tss: 45,
    description: 'Low-volume neuromuscular session focused on raw power output.',
    steps: [
      '15 min warm-up',
      '6 x 10 s standing start from low cadence, 4 min full recovery',
      '5 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 6, on: { d: 10, p: 2.2 }, off: { d: 240, p: 0.5 } },
      cd(300),
    ],
  },
  {
    id: 'ana-5',
    headline: '20 x 30/30 @ 150% FTP',
    title: 'Anaerobic 30/30 Repeats',
    category: 'anaerobic',
    subcategory: 'repeats',
    level: 'advanced',
    tss: 72,
    description: 'Repeatable 30/30 efforts that drain and reload the anaerobic tank.',
    steps: [
      '15 min warm-up',
      '4 sets of 5 x (30 s @ 150% FTP, 30 s easy), 5 min between sets',
      '8 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 5, trailingOff: true, on: { d: 30, p: 1.5 }, off: { d: 30, p: 0.5 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 5, trailingOff: true, on: { d: 30, p: 1.5 }, off: { d: 30, p: 0.5 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 5, trailingOff: true, on: { d: 30, p: 1.5 }, off: { d: 30, p: 0.5 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 5, trailingOff: true, on: { d: 30, p: 1.5 }, off: { d: 30, p: 0.5 } },
      cd(480),
    ],
  },
  {
    id: 'ana-6',
    headline: '5 x 1 min @ 135% FTP',
    title: 'Race-Winning Minutes',
    category: 'anaerobic',
    subcategory: 'efforts',
    level: 'intermediate',
    tss: 68,
    description: 'Hard but sub-maximal one-minute efforts to rehearse attacks.',
    steps: [
      '16 min warm-up',
      '5 x 1 min @ 135% FTP, 4 min easy between',
      '9 min cool-down',
    ],
    intervals: [
      wu(960),
      { repeat: 5, on: { d: 60, p: 1.35 }, off: { d: 240, p: 0.5 } },
      cd(540),
    ],
  },
  // Workout supplied by Cody Hamilton
  {
    id: 'ana-7',
    headline: '4 x 1 min max efforts',
    title: 'Maximal Minute Repeats',
    category: 'anaerobic',
    subcategory: 'efforts',
    level: 'advanced',
    tss: 60,
    description: 'Four all-out one-minute efforts with very long recoveries so each can be truly maximal — a test of anaerobic power and repeatability.',
    steps: [
      '15 min warm-up',
      '4 x 1 min all-out (max), 20 min easy between',
      '10 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 4, on: { d: 60, p: 1.5 }, off: { d: 1200, p: 0.5 } },
      cd(600),
    ],
  },
  {
    id: 'ana-8',
    headline: '3 x 5 min seated 30/30 max efforts',
    title: 'Crit Repeatability 30/30s',
    category: 'anaerobic',
    subcategory: 'repeats',
    level: 'advanced',
    tss: 78,
    description: 'Three five-minute blocks of seated 30-second max efforts on 30-second recoveries. Power fades across each block (think 600/500/400/400/400 W) — built to sharpen the repeatable, seated punch a criterium demands. Stay seated to load the muscles the way a crit does.',
    steps: [
      '18 min warm-up: 8 min Zone 1, 5 min progressive tempo, 5 min Zone 1',
      '3 x 5 min blocks: 5 x (30 s seated max, 30 s easy), power fades within each block',
      '5 min easy between blocks',
      '10 min cool-down',
    ],
    intervals: [
      { d: 480, p: 0.5 },
      { kind: 'ramp', d: 300, p: [0.65, 0.85] },
      { kind: 'rest', d: 300, p: 0.5 },
      // Block 1 — seated max 30/30, decaying then holding
      { kind: 'active', d: 30, p: 2.0 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.65 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.4 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.35 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.35 }, { kind: 'rest', d: 300, p: 0.5 },
      // Block 2
      { kind: 'active', d: 30, p: 2.0 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.65 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.4 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.35 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.35 }, { kind: 'rest', d: 300, p: 0.5 },
      // Block 3
      { kind: 'active', d: 30, p: 2.0 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.65 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.4 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.35 }, { kind: 'rest', d: 30, p: 0.5 },
      { kind: 'active', d: 30, p: 1.35 }, { kind: 'rest', d: 30, p: 0.5 },
      cd(600),
    ],
  },
]
