import { wu, cd } from '../helpers.js'

// Endurance workouts. See src/data/workouts.js for the field reference.
export const endurance = [
  {
    id: 'end-1',
    headline: '70 min @ Zone 2',
    title: 'Aerobic Base Ride',
    category: 'endurance',
    subcategory: 'zone2',
    level: 'intermediate',
    tss: 75,
    description: 'Long steady ride in Zone 2 to build aerobic capacity and fat metabolism.',
    steps: [
      '10 min warm-up, easy spin',
      '70 min @ Zone 2 (56–75% FTP), steady cadence 85–95 rpm',
      '10 min cool-down',
    ],
    intervals: [wu(600), { d: 4200, p: 0.65 }, cd(600)],
  },
  {
    id: 'end-2',
    headline: '40 min @ Zone 1',
    title: 'Recovery Spin',
    category: 'endurance',
    subcategory: 'recovery',
    level: 'beginner',
    tss: 25,
    description: 'Very light flush ride for active recovery between hard days.',
    steps: ['40 min @ Zone 1 (< 55% FTP), light pressure, high cadence'],
    intervals: [{ d: 2400, p: 0.5 }],
  },
  {
    id: 'end-3',
    headline: '6 x 3 min cadence spin-ups',
    title: 'Endurance with Cadence Drills',
    category: 'endurance',
    subcategory: 'zone2',
    level: 'intermediate',
    tss: 65,
    description: 'Steady aerobic ride with cadence work to improve pedalling efficiency.',
    steps: [
      '15 min warm-up',
      '6 x (3 min high cadence 100–110 rpm, 3 min normal cadence) in Zone 2',
      '15 min steady Zone 2',
      '6 min cool-down',
    ],
    intervals: [wu(900), { d: 3240, p: 0.65 }, cd(360)],
  },
  {
    id: 'end-4',
    headline: '120 min @ Zone 2',
    title: 'Long Aerobic Endurance',
    category: 'endurance',
    subcategory: 'zone2',
    level: 'intermediate',
    tss: 130,
    description: 'Big aerobic volume day for base periods and gran fondo prep.',
    steps: [
      '15 min warm-up',
      '120 min @ Zone 2, mostly seated, fuel every 30 min',
      '15 min cool-down',
    ],
    intervals: [wu(900), { d: 7200, p: 0.65 }, cd(900)],
  },
  {
    id: 'end-5',
    headline: '2 x 25 min @ LT1',
    title: 'LT1 Sustained Ride',
    category: 'endurance',
    subcategory: 'lt1',
    level: 'advanced',
    tss: 90,
    description: 'Long blocks right at the aerobic threshold (LT1) to lift fat-max power.',
    steps: [
      '15 min warm-up',
      '2 x 25 min @ LT1 (top of Zone 2 / 75–80% FTP), 10 min easy between',
      '15 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 2, on: { d: 1500, p: 0.78 }, off: { d: 600, p: 0.55 } },
      cd(900),
    ],
  },
  {
    id: 'end-6',
    headline: '3 x 15 min @ LT1',
    title: 'Tempo-Tipped Endurance',
    category: 'endurance',
    subcategory: 'lt1',
    level: 'advanced',
    tss: 115,
    description: 'Long ride with LT1/low-tempo surges to add aerobic stress without going deep.',
    steps: [
      '15 min warm-up',
      '3 x (15 min @ LT1–low tempo, 10 min Zone 2)',
      '25 min steady Zone 2',
      '15 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 3, on: { d: 900, p: 0.8 }, off: { d: 600, p: 0.65 } },
      { d: 1500, p: 0.65 },
      cd(900),
    ],
  },
  {
    id: 'end-7',
    headline: '60 min @ Zone 1',
    title: 'Easy Coffee Spin',
    category: 'endurance',
    subcategory: 'recovery',
    level: 'beginner',
    tss: 35,
    description: 'Relaxed social-pace recovery ride to keep the legs turning.',
    steps: ['60 min @ Zone 1 (< 55% FTP), conversational, no pressure on the pedals'],
    intervals: [{ d: 3600, p: 0.5 }],
  },
  // Workout supplied by Cody Hamilton
  {
    id: 'end-8',
    headline: '6 x 20 min @ LT1',
    title: 'LT1 Big Day 6x20',
    category: 'endurance',
    subcategory: 'lt1',
    level: 'pro',
    tss: 175,
    description: 'A huge aerobic day — six long blocks at LT1 to maximise fat-max power and durability.',
    steps: [
      '15 min warm-up',
      '6 x 20 min @ LT1 (~78% FTP), 5 min easy between',
      '10 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 6, on: { d: 1200, p: 0.78 }, off: { d: 300, p: 0.65 } },
      cd(600),
    ],
  },
  {
    id: 'end-9',
    headline: '4 x 20 min @ LT1',
    title: 'LT1 Four-Twenty',
    category: 'endurance',
    subcategory: 'lt1',
    level: 'advanced',
    tss: 145,
    description: 'Four sustained LT1 blocks with short recoveries to build durable aerobic power.',
    steps: [
      '12 min warm-up',
      '4 x 20 min @ LT1 (~78% FTP), 5 min easy between',
      '8 min cool-down',
    ],
    intervals: [
      wu(720),
      { repeat: 4, on: { d: 1200, p: 0.78 }, off: { d: 300, p: 0.6 } },
      cd(480),
    ],
  },
]
