import { wu, cd } from '../helpers.js'

// Middle Intensity workouts. See src/data/workouts.js for the field reference.
export const middle = [
  {
    id: 'mid-1',
    headline: '2 x 20 min @ 90% FTP',
    title: 'Sweet Spot 2x20',
    category: 'middle',
    subcategory: 'sweetspot',
    level: 'intermediate',
    tss: 85,
    description: 'Classic sweet spot session to raise sustainable power efficiently.',
    steps: [
      '15 min warm-up',
      '2 x 20 min @ 88–94% FTP, 8 min easy between',
      '7 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 2, on: { d: 1200, p: 0.91 }, off: { d: 480, p: 0.55 } },
      cd(420),
    ],
  },
  {
    id: 'mid-2',
    headline: '3 x 10 min @ Tempo',
    title: 'Tempo Builder',
    category: 'middle',
    subcategory: 'tempo',
    level: 'beginner',
    tss: 65,
    description: 'Approachable tempo work to bridge from base into intensity.',
    steps: [
      '12 min warm-up',
      '3 x 10 min @ Zone 3 (76–87% FTP), 5 min easy between',
      '8 min cool-down',
    ],
    intervals: [
      wu(720),
      { repeat: 3, on: { d: 600, p: 0.82 }, off: { d: 300, p: 0.55 } },
      cd(480),
    ],
  },
  {
    id: 'mid-3',
    headline: '3 x 12 min @ FTP',
    title: 'Threshold 3x12',
    category: 'middle',
    subcategory: 'threshold',
    level: 'advanced',
    tss: 100,
    description: 'Sustained threshold intervals to push FTP upward.',
    steps: [
      '15 min warm-up',
      '3 x 12 min @ 95–100% FTP, 7 min recovery',
      '15 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 3, on: { d: 720, p: 0.98 }, off: { d: 420, p: 0.5 } },
      cd(900),
    ],
  },
  {
    id: 'mid-4',
    headline: '2 x 20 min over-unders @ 90/105% FTP',
    title: 'Sweet Spot Over-Unders',
    category: 'middle',
    subcategory: 'sweetspot',
    level: 'advanced',
    tss: 95,
    description: 'Over-under intervals to handle changes of pace at threshold.',
    steps: [
      '15 min warm-up',
      '2 x [4 x (2 min @ 105% FTP, 3 min @ 90% FTP)], 5 min easy between',
      '15 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 4, trailingOff: true, on: { d: 120, p: 1.05 }, off: { d: 180, p: 0.9 } },
      { kind: 'rest', d: 300, p: 0.55 },
      { repeat: 4, trailingOff: true, on: { d: 120, p: 1.05 }, off: { d: 180, p: 0.9 } },
      cd(900),
    ],
  },
  {
    id: 'mid-5',
    headline: '2 x 25 min @ Tempo',
    title: 'Tempo Endurance Combo',
    category: 'middle',
    subcategory: 'tempo',
    level: 'advanced',
    tss: 110,
    description: 'Extended tempo blocks inside a longer aerobic ride.',
    steps: [
      '15 min warm-up',
      '2 x 25 min @ Zone 3 tempo, 10 min Zone 2 between',
      '10 min steady Zone 2',
      '15 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 2, on: { d: 1500, p: 0.82 }, off: { d: 600, p: 0.65 } },
      { d: 600, p: 0.65 },
      cd(900),
    ],
  },
  {
    id: 'mid-6',
    headline: '4 x 8 min over-unders @ FTP',
    title: 'Threshold Over-Unders 4x8',
    category: 'middle',
    subcategory: 'threshold',
    level: 'advanced',
    tss: 98,
    description: 'Threshold-focused over-unders to build resilience right at FTP.',
    steps: [
      '15 min warm-up',
      '4 x 8 min (alternate 1 min @ 100% / 1 min @ 95% FTP), 5 min easy between',
      '10 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 4, trailingOff: true, on: { d: 60, p: 1.0 }, off: { d: 60, p: 0.95 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 4, trailingOff: true, on: { d: 60, p: 1.0 }, off: { d: 60, p: 0.95 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 4, trailingOff: true, on: { d: 60, p: 1.0 }, off: { d: 60, p: 0.95 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 4, trailingOff: true, on: { d: 60, p: 1.0 }, off: { d: 60, p: 0.95 } },
      cd(600),
    ],
  },
  // Workout supplied by Cody Hamilton
  {
    id: 'mid-7',
    headline: '6 x 10 min progressive LT2 (85→97% FTP)',
    title: 'Progressive Threshold 6x10',
    category: 'middle',
    subcategory: 'threshold',
    level: 'pro',
    tss: 120,
    description: 'Six 10-minute blocks climbing from upper sweet spot to threshold (LT2), each harder than the last.',
    steps: [
      '15 min warm-up',
      '6 x 10 min progressive: 85, 87, 90, 92, 95, 97% FTP, 90 s easy between',
      '10 min cool-down',
    ],
    intervals: [
      wu(900),
      { d: 600, p: 0.85 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.87 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.9 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.92 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.95 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.97 },
      cd(600),
    ],
  },
  // Workout supplied by Cody Hamilton
  {
    id: 'mid-9',
    headline: '2 x 20 min @ 100% FTP',
    title: 'Threshold 2x20',
    category: 'middle',
    subcategory: 'threshold',
    level: 'advanced',
    tss: 95,
    description: 'Two classic 20-minute efforts right at FTP — the benchmark threshold session.',
    steps: [
      '15 min warm-up',
      '2 x 20 min @ 100% FTP, 10 min easy between',
      '10 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 2, on: { d: 1200, p: 1.0 }, off: { d: 600, p: 0.5 } },
      cd(600),
    ],
  },
  // Workout supplied by Cody Hamilton
  {
    id: 'mid-10',
    headline: '2 x 21 min sweet spot + surges',
    title: 'Sweet Spot with Surges',
    category: 'middle',
    subcategory: 'sweetspot',
    level: 'advanced',
    tss: 90,
    description: 'Two 21-minute sweet-spot blocks with a sharp 10-second surge every 3 minutes to jolt the legs.',
    steps: [
      '15 min warm-up',
      '2 x 21 min @ 85–90% FTP with a 10 s surge @ 170–200% FTP every 3 min, 5 min between',
      '10 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 7, trailingOff: true, on: { d: 170, p: 0.875 }, off: { d: 10, p: 1.85 } },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 7, trailingOff: true, on: { d: 170, p: 0.875 }, off: { d: 10, p: 1.85 } },
      cd(600),
    ],
  },
  // Workout supplied by Cody Hamilton
  {
    id: 'mid-11',
    headline: '3 x 15 min over-unders @ 120/90% FTP',
    title: 'Over-Under 3x15 (1:4)',
    category: 'middle',
    subcategory: 'threshold',
    level: 'pro',
    tss: 120,
    description: 'Three 15-minute over-under blocks alternating 1 min @ 120% with 4 min @ 90% FTP, with full recoveries.',
    steps: [
      '15 min warm-up',
      '3 x 15 min as 3 x (1 min @ 120% FTP, 4 min @ 90% FTP), 10 min easy between',
      '10 min cool-down',
    ],
    intervals: [
      wu(900),
      { repeat: 3, trailingOff: true, on: { d: 60, p: 1.2 }, off: { d: 240, p: 0.9 } },
      { kind: 'rest', d: 600, p: 0.5 },
      { repeat: 3, trailingOff: true, on: { d: 60, p: 1.2 }, off: { d: 240, p: 0.9 } },
      { kind: 'rest', d: 600, p: 0.5 },
      { repeat: 3, trailingOff: true, on: { d: 60, p: 1.2 }, off: { d: 240, p: 0.9 } },
      cd(600),
    ],
  },
  {
    id: 'mid-12',
    headline: '10 x 4 min @ LT2',
    title: 'LT2 10x4',
    category: 'middle',
    subcategory: 'threshold',
    level: 'advanced',
    tss: 90,
    description: 'A long threshold session with ten four-minute LT2 reps and one-minute recoveries, built around a steady aerobic warm-up.',
    steps: [
      '8 min warm-up in Zone 1',
      '5 min build up to tempo',
      '5 min easy spin',
      '10 x 4 min @ LT2 (~92% FTP), 1 min easy between',
      '5 min easy recovery',
    ],
    intervals: [
      { d: 480, p: 0.5 },
      { kind: 'ramp', d: 300, p: [0.55, 0.8] },
      { kind: 'rest', d: 300, p: 0.5 },
      { repeat: 10, on: { d: 240, p: 0.92 }, off: { d: 60, p: 0.5 } },
      { d: 300, p: 0.5 },
    ],
  },
  {
    id: 'mid-13',
    headline: '5 x 10 min progressive LT2',
    title: 'Progressive LT2 5x10',
    category: 'middle',
    subcategory: 'threshold',
    level: 'advanced',
    tss: 115,
    description: 'Five sustained LT2 intervals that climb in difficulty across the set.',
    steps: [
      '20 min Zone 1',
      '6 min LT1',
      '3 min LT2',
      '15 min LT1',
      '5 x 10 min progressive LT2: 88, 90, 92, 95, 97% FTP',
      '90 s easy between intervals',
      '10 min Zone 1 cool-down',
    ],
    intervals: [
      { d: 1200, p: 0.5 },
      { d: 360, p: 0.78 },
      { d: 180, p: 0.9 },
      { d: 900, p: 0.78 },
      { d: 600, p: 0.88 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.9 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.92 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.95 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 600, p: 0.97 },
      cd(600),
    ],
  },
  {
    id: 'mid-14',
    headline: '7 x 7 min progressive LT2',
    title: 'Progressive Threshold 7x7',
    category: 'middle',
    subcategory: 'threshold',
    level: 'advanced',
    tss: 110,
    description: 'Seven seven-minute efforts that start just below LT2 and finish above FTP, giving a smooth but demanding progression.',
    steps: [
      '10 min Zone 1',
      '6 min LT1',
      '3 min LT2',
      '10 min Zone 1',
      '7 x 7 min progressive: 90, 92, 94, 96, 98, 100, 102% FTP',
      '90 s easy between intervals',
      '10 min Zone 1 cool-down',
    ],
    intervals: [
      { d: 600, p: 0.5 },
      { d: 360, p: 0.78 },
      { d: 180, p: 0.9 },
      { d: 600, p: 0.5 },
      { d: 420, p: 0.9 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 420, p: 0.92 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 420, p: 0.94 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 420, p: 0.96 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 420, p: 0.98 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 420, p: 1.0 },
      { kind: 'rest', d: 90, p: 0.5 },
      { d: 420, p: 1.02 },
      cd(600),
    ],
  },
]
